---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: teste2
  namespace: wego-system
spec:
  interval: 1m0s
  path: ./git@github.com:rtfae/demoweave.git
  prune: true
  sourceRef:
    kind: GitRepository
    name: teste2

